# Generated by Django 5.2.13 on 2026-05-14 19:28

import django.core.validators
import django.db.models.deletion
import opaque_keys.edx.django.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openedx_catalog', '0001_initial'),
        ('openedx_plugin_sample', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseAverageRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum_stars', models.PositiveIntegerField(default=0)),
                ('rating_count', models.PositiveIntegerField(default=0)),
                ('average_stars', models.FloatField(blank=True, help_text='Null when rating_count == 0.', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='average_rating', to='openedx_catalog.courserun')),
            ],
        ),
        migrations.CreateModel(
            name='UnitRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_key', opaque_keys.edx.django.models.UsageKeyField(db_index=True, help_text="e.g. 'block-v1:edX+DemoX+Demo_Course+type@vertical+block@abc123'", max_length=255)),
                ('stars', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_run', models.ForeignKey(help_text='Denormalized from usage_key so we can aggregate per course cheaply.', on_delete=django.db.models.deletion.CASCADE, related_name='unit_ratings', to='openedx_catalog.courserun')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'usage_key'), name='unique_user_unit_rating')],
            },
        ),
    ]
