name: Python CI

on:
  pull_request:
    branches:
      - "**"
  # This is so we can call CI locally from other workflows that might want to
  # run CI before doing whatever task they're doing.  Like the release workflow.
  workflow_call:

defaults:
  run:
    working-directory: "./backend-plugin-sample"

jobs:
  run_tests:
    name: tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.12"]
        toxenv: [quality, docs, pii_check, django52, django60]
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - name: setup python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@38f3f104447c67c051c4a08e39b64a148898af3a # v4.2.0

      - name: Install CI dependencies
        run: uv sync --group ci

      - name: Run Tests
        env:
          TOXENV: ${{ matrix.toxenv }}
        run: uv run tox

      - name: Run coverage
        if: matrix.python-version == '3.12' && matrix.toxenv == 'django52'
        uses: codecov/codecov-action@b9fd7d16f6d7d1b5d2bec1a2887e65ceed900238 # v4.6.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unittests
          fail_ci_if_error: true
          working-directory: "./backend-plugin-sample"
